baseURL = "https://www.mumble.info/"
languageCode = "en-us"
title = "Mumble"
publishDir = "../public"

disableKinds = ["taxonomy","taxonomyTerm"]

[params]
  description = "Mumble is a free, open source, low latency, high quality voice chat application."
  gitSite = "GitHub"
  gitWebURL = "https://github.com/mumble-voip/mumble-www/"

[permalinks]
  blog = "/blog/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Render HTML in Markdown files (and “potentially dangerous links”).
      unsafe = true

# See the config folder for additional configuration
